h<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://za.gl/links/go");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '_method=POST&_csrfToken=ba4e0a174af0bcc6f2f918107a437c6e821bb9fa2947996afcdbadf98117db396ef5ab807a2667626b37f624007c2f6f67804f7aa11a9d1bb584d02e9c65c01a&ad_form_data=MGNkNDc4NGJjN2Q1ZWJkY2I2Yjg5ODhhN2U0YzczOWFkODgyODg0N2EzNDI4MjFjY2JiODg1NWIwYWM1NWNiZIpqUQQLkRXIXga4p%"2BMYyhOmclbFReh0pl9jJ55%2Bc5Wtsw7X%2BuD52Q6i9DYXeeMoiKMOiI9uRGt4phqJXFzUtVoMaXoI0hD0adKpjmvqfjTfy7%2FjWqRmSNE42E5Ox6b12gll9weyA2qvjEkkGQsya7Ve%2FjgFL4gN1iZLmb076hpjkLHDLJf%2FURIdR13FsavZdZrRMpfYNtqV%2BQdg%2BiwY1JCQXjSDHvhExC2%2Fqc%2FphQcN&_Token%5Bfields%5D=7f1ea607eb8e371ecb6e43986d380c7636593d05%253Aad_form_data&_Token%5Bunlocked%5D=adcopy_challenge%257Cadcopy_response%257Ccoinhive-captcha-token%257Cg-recaptcha-response"');
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = "User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:63.0) Gecko/20100101 Firefox/63.0";
$headers[] = "Accept: application/json, text/javascript, */*; q=0.01";
$headers[] = "Accept-Language: id,en-US;q=0.7,en;q=0.3";
$headers[] = "Referer: https://za.gl/GYzTT";
$headers[] = "Content-Type: application/x-www-form-urlencoded; charset=UTF-8";
$headers[] = "X-Requested-With: XMLHttpRequest";
$headers[] = "Connection: keep-alive";
$headers[] = 'Cookie: __cfduid=dee0d9207ec3121f30fed7118585816f51542198924; AppSession=imi7p5ikbq09k0124ioi4gu6b4; csrfToken=ba4e0a174af0bcc6f2f918107a437c6e821bb9fa2947996afcdbadf98117db396ef5ab807a2667626b37f624007c2f6f67804f7aa11a9d1bb584d02e9c65c01a; visitor=Q2FrZQ%"3D%3D.NDExZGExYjM5NzAwNTY4ZDk3MTAzM2U5OTE0OTQ0YmQxZDllMGY3NDhlYWZhOTM0MTU0NjY5ZTM2YmM0NjFlN37ESicB5nL%2BRM%2BRiIirLkz%2FSln99M8LVPCeDGDv3dCtjwyLMJXLTPf4Lb9vKeIJOeSGp9Tae%2Bfx%2BP2owTECMNTz4vDuVUWkqdccH7267Ksb;';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
else
{
	echo "$result";
}
curl_close ($ch);

?>